---
permalink: online-help/concept-all-workloads.html 
sidebar: sidebar 
keywords: workloads,workloads 
summary: すべてのワークロードビューには、データセンター内のクラスタで使用可能なすべてのワークロードのリストが表示されます。 
---
= すべてのワークロード
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
すべてのワークロードビューには、データセンター内のクラスタで使用可能なすべてのワークロードのリストが表示されます。

すべてのワークロードビューには、 Unified Manager で管理されている ONTAP クラスタに関連付けられているストレージワークロードが表示されます。このページでは、ストレージワークロードにストレージ効率化ポリシーとパフォーマンスサービスレベルを割り当てることもできます。

Unified Manager にクラスタを追加すると、 FlexGroup ボリュームとそのコンスティチュエントを除く各クラスタのストレージワークロードが自動的に検出されてこのページに表示されます。

Unified Managerは、ストレージワークロードでI/O処理が開始されたあとに、推奨事項（推奨されるパフォーマンスサービスレベル）に対するワークロードの分析を開始します。新たに検出されたストレージワークロードで I/O 処理が行われていない場合、ステータスは「 I/O を待機中」になります。ストレージワークロードで I/O 処理が開始されると、 Unified Manager が分析を開始し、ワークロードのステータスが「学習中 ... 」に変わります。分析が完了すると（I/O処理の開始から24時間以内）、ストレージワークロードに対して推奨されるパフォーマンスサービスレベルが表示されます。

[* Workloads * > * all workloads * （ * すべてのワークロード * ） ] オプションを使用すると、複数のタスクを実行できます。

* ストレージワークロードを追加またはプロビジョニングする
* ワークロードのリストを表示してフィルタリングします
* 個 々 のストレージワークロードにパフォーマンスサービスレベルを割り当てます
* 未割り当てのすべてのワークロードに、システム推奨のパフォーマンスサービスレベルを割り当てます
* ストレージワークロードにストレージ効率化ポリシーを割り当てます




== ストレージワークロードを追加またはプロビジョニングする

サポートされる LUN （ iSCSI と FCP の両プロトコルをサポート）、 NFS ファイル共有、 SMB 共有にストレージワークロードを追加またはプロビジョニングできます。



== ワークロードの表示とフィルタリング

すべてのワークロード画面では、データセンター内のすべてのワークロードを表示したり、割り当てられているパフォーマンスサービスレベルまたはワークロード名に基づいて特定のストレージワークロードを検索したりできます。フィルタアイコンを使用して、検索条件を入力できます。ホストクラスタや Storage VM など、さまざまなフィルタ条件で検索できます。容量の合計*オプションを選択すると、ワークロードの合計容量で検索できます。容量はバイトレベルで比較されるため、入力したフィルタ条件によって返されるワークロードの数が変わることがあります。ホストクラスタやStorage VMなどのワークロードのストレージ情報、パフォーマンスサービスレベルとストレージ効率化ポリシーがある場合はそれらも表示されます。

また、このページではワークロードのパフォーマンスの詳細を確認することもできます。ワークロードの IOPS 、容量、レイテンシに関する詳細情報を表示するには、「 * 列の選択 / 順序」ボタンをクリックし、表示する列を選択します。パフォーマンスビューの列にはワークロードの平均 IOPS とピーク IOPS が表示され、ワークロードアナライザのアイコンをクリックすると詳細な IOPS 分析を確認できます。IOPS 分析ポップアップの * ワークロードの分析ボタンをクリックすると、ワークロード分析ページが開き、期間を選択して、選択したワークロードのレイテンシ、スループット、容量のトレンドを確認できます。Workload Analyzer の詳細については、 Workload Analyzer を使用したワークロードのトラブルシューティング _ を参照してください

link:concept-troubleshooting-workloads-using-the-workload-analyzer.html["Workload Analyzer を使用したワークロードのトラブルシューティング"]



== ストレージワークロードにパフォーマンスサービスレベルを割り当てています

1つまたは複数のストレージワークロードにパフォーマンスサービスレベルを割り当てることができます。画面のさまざまなオプションを使用して、特定のまたはシステム推奨のパフォーマンスサービスレベルをワークロードに割り当てることができます。



== 未割り当てのすべてのワークロードにシステム推奨のパフォーマンスサービスレベルを割り当てています

ワークロードにシステム推奨のパフォーマンスサービスレベルがある場合は、PSLが割り当てられていないデータセンター内のすべてのストレージワークロードにパフォーマンスサービスレベルを割り当てることができます。システム推奨のパフォーマンスサービスレベルがないワークロードには、この機能は無効です。この機能を使用するには、 * Assign System Recommended PSL * ボタンをクリックします。未割り当てのストレージワークロードに適したパフォーマンスサービスレベルが内部的に評価され、パフォーマンスサービスレベルを割り当てることができるワークロードの総数が表示されます。



== ストレージワークロードにストレージ効率化ポリシーを割り当てます

1つまたは複数のストレージワークロードにストレージ効率化ポリシーを割り当てることができます。画面のさまざまなオプションを使用して、特定のストレージ効率化ポリシーをストレージワークロードに割り当てることができます。



== パフォーマンスサービスレベルとストレージ効率化ポリシーを一緒に割り当てています

一緒に1つのワークロードにパフォーマンスサービスレベルとストレージ効率化ポリシーを割り当てることができます。次の手順を実行します。

. 行の編集アイコンをクリックし、*編集*をクリックします。
+
[ 割り当てられているパフォーマンスサービスレベル * ] フィールドと [ ストレージ効率化ポリシー * ] フィールドが有効になります。

. 必要なパフォーマンスサービスレベルとストレージ効率化ポリシーを選択します。
. チェックマークアイコンをクリックして変更を適用します。




== ワークロードのパフォーマンスと容量の条件を分析します

パフォーマンスビュー * 列の棒グラフアイコンをクリックすると、ワークロードに関するパフォーマンス情報を表示してトラブルシューティングに役立てることができます。ワークロードの分析ページにパフォーマンスと容量のグラフを表示してオブジェクトを分析するには、 * ワークロードの分析 * ボタンをクリックします。
