---
permalink: online-help/concept-managing-performance-service-levels.html 
sidebar: sidebar 
keywords:  
summary: パフォーマンスサービスレベルを使用すると、ワークロードに対してパフォーマンスとストレージの目標を定義できます。ワークロードの作成時または編集時に、パフォーマンスサービスレベルをワークロードに割り当てることができます。 
---
= パフォーマンスサービスレベルの管理
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
パフォーマンスサービスレベルを使用すると、ワークロードに対してパフォーマンスとストレージの目標を定義できます。ワークロードの作成時または編集時に、パフォーマンスサービスレベルをワークロードに割り当てることができます。

ストレージリソースは、サービスレベル目標（ SLO ）に基づいて管理および監視されます。SLOは、パフォーマンスと容量に基づくサービスレベルアグリーメントによって定義されます。Unified Managerでは、SLOと言った場合、ネットアップストレージで実行されているアプリケーションのパフォーマンスサービスレベルの定義を意味します。ストレージサービスの内容は、基盤となるリソースのパフォーマンスと利用率に基づいて決定されます。パフォーマンスサービスレベルは、ストレージサービス目標の概要 です。ストレージプロバイダは、パフォーマンスサービスレベルを使用してワークロードに対して目標とするパフォーマンスと容量を指定できます。

Unified Managerには、「最高レベルのパフォーマンス」、「パフォーマンス」、「バリュー」という複数のパフォーマンスサービスレベルが事前に定義（組み込まれて）あります。「最高レベルのパフォーマンス」、「パフォーマンス」、「バリュー」の各パフォーマンスサービスレベルは、データセンターの一般的なストレージワークロードのほとんどに当てはまります。Unified Managerには、データベースアプリケーションのパフォーマンスサービスレベルとして、「データベースログ用の最高レベル」、「データベース共有データ用の最高レベル」、「データベースデータ用の最高レベル」の3つのレベルもあります。これらは、バーストIOPSをサポートする非常にハイパフォーマンスなパフォーマンスサービスレベルであり、スループットの要求が最も厳しいデータベースアプリケーションに適しています。事前定義されたパフォーマンスサービスレベルが要件を満たさない場合は、事前定義されたパフォーマンスサービスレベルの定義に基づいて新しいパフォーマンスサービスレベルを作成できます。

パフォーマンスサービスレベルには、ポリシー*>*パフォーマンスサービスレベル*ページからアクセスしたり、ストレージプロバイダAPIを使用したりできます。ストレージワークロードを個別に管理する必要がないため、パフォーマンスサービスレベルを割り当ててストレージワークロードを管理すると便利です。変更についても、個別に管理するのではなく、別のパフォーマンスサービスレベルを再割り当てして管理することができます。

システム定義のパフォーマンスサービスレベル、またはワークロードに現在割り当てられているパフォーマンスサービスレベルは変更できません。ワークロードに割り当てられているPSL、または他に使用可能なパフォーマンスサービスレベルがないPSLは削除できません。

パフォーマンスサービスレベルページには使用可能なパフォーマンスサービスレベルポリシーが表示され、それらを追加、編集、削除することができます。このページには、次の情報が表示されます。

[cols="1a,1a"]
|===
| フィールド | 説明 


 a| 
名前
 a| 
パフォーマンスサービスレベルの名前。



 a| 
を入力します
 a| 
システム定義のポリシーかユーザ定義のポリシーか。



 a| 
想定 IOPS
 a| 
LUN またはファイル共有でアプリケーションが実行すると想定される最小 IOPS 。想定 IOPS は、ストレージオブジェクトの割り当てサイズに基づいて、割り当てられる最小想定 IOPS を指定します。



 a| 
最大 IOPS
 a| 
LUN またはファイル共有でアプリケーションが実行できる最大 IOPS 。ピーク IOPS は、ストレージオブジェクトの割り当てサイズまたは使用済みサイズに基づいて、割り当て可能な最大 IOPS を指定します。

ピーク IOPS は割り当てポリシーを基準にして算出されます。割り当てポリシーは、 allocated-space または used-space のいずれかです。割り当てポリシーが allocated-space の場合は、ストレージオブジェクトのサイズに基づいてピーク IOPS が計算されます。割り当てポリシーが used-space の場合は、 Storage Efficiency 機能の効果を考慮し、ストレージオブジェクトに格納されているデータの量に基づいてピーク IOPS が計算されます。デフォルトでは、割り当てポリシーは used-space に設定されています。



 a| 
絶対最小 IOPS
 a| 
絶対最小IOPSは、想定IOPSがこの値より低い場合に使用されます。有効な値は400~1000です。絶対最小IOPSの範囲は、次のように計算されます。

最小値は1000 /想定レイテンシです

システム定義のパフォーマンスサービスレベルのデフォルト値は、次のように計算されます。

* 最高レベルのパフォーマンス：想定 IOPS ≧ 6144/TB の場合、絶対最小 IOPS=1000
* パフォーマンス： 6144/TB > 想定 IOPS ≧ 2048/TB の場合、絶対最小 IOPS=500
* バリュー： 2048/TB > 想定 IOPS ≧ 128/TB の場合、絶対最小 IOPS=75


システム定義のデータベースのパフォーマンスサービスレベルのデフォルト値は、次のように計算されます。

* データベースログの最高レベル：想定 IOPS ≧ 22528 の場合、絶対最小 IOPS =4000
* データベース共有データの最大 IOPS ：想定 IOPS ≧ 16384 の場合、絶対最小 IOPS=2000
* データベースデータの最高レベル：想定 IOPS ≧ 12288 の場合、絶対最小 IOPS=2000




 a| 
想定レイテンシ
 a| 
処理あたりのミリ秒（ ms/op ）で表したストレージ IOPS の想定レイテンシ。



 a| 
容量
 a| 
クラスタ内の使用可能容量と使用済み容量の合計。



 a| 
ワークロード
 a| 
パフォーマンスサービスレベルが割り当てられているストレージワークロードの数。

|===
ワークロードが過去1時間の想定レイテンシ値を30%超えた場合、Unified Managerは次のいずれかのイベントを生成して、潜在的なパフォーマンス問題 をユーザに通知します。「パフォーマンス・サービス・レベル・ポリシーで定義されたワークロードのボリューム・レイテンシしきい値を超過」または「パフォーマンス・サービス・レベル・ポリシーで定義されたワークロードのLUNレイテンシしきい値を超過」

次の表に、システム定義のパフォーマンスサービスレベルに関する情報を示します。

[cols="1a,1a,1a,1a,1a,1a"]
|===
| パフォーマンスサービスレベル | 概要とユースケース | 想定レイテンシ（ミリ秒 / 処理） | 最大 IOPS | 想定 IOPS | 絶対最小 IOPS 


 a| 
卓越したパフォーマンス
 a| 
非常に高いスループットを非常に低いレイテンシで実現します

レイテンシの影響を受けやすいアプリケーションに最適です
 a| 
1.
 a| 
12288
 a| 
6144
 a| 
1000



 a| 
パフォーマンス
 a| 
高いスループットを低いレイテンシで実現

データベースや仮想アプリケーションに最適です
 a| 
2.
 a| 
4096
 a| 
2048
 a| 
500ドル



 a| 
価値
 a| 
高いストレージ容量を適度なレイテンシで実現します

E メール、 Web コンテンツ、ファイル共有、バックアップターゲットなどの大容量アプリケーションに最適です
 a| 
17
 a| 
512
 a| 
128
 a| 
七五



 a| 
データベースログの「最高レベル」
 a| 
最小のレイテンシで最大スループットを実現

データベースログをサポートするデータベースアプリケーションに最適です。データベースログは非常にバースト性が高く、常にロギングが必要であるため、この PSL は最高のスループットを提供します。
 a| 
1.
 a| 
45056
 a| 
22528
 a| 
4 、 000



 a| 
データベース共有データ用の Extreme
 a| 
非常に高いスループットを最小のレイテンシで実現

共通のデータストアに格納されていて、データベース間で共有されているデータベースアプリケーションデータに最適です。
 a| 
1.
 a| 
32768
 a| 
16384
 a| 
2000年



 a| 
データベースデータ用の Extreme
 a| 
高いスループットを最小のレイテンシで実現

データベーステーブル情報やメタデータなどのデータベースアプリケーションデータに最適です。
 a| 
1.
 a| 
24576
 a| 
12288
 a| 
2000年

|===


== カスタムのパフォーマンスサービスレベルを作成する際のガイドライン

既存のパフォーマンスサービスレベルがストレージワークロードのサービスレベル目標（SLO）の要件を満たしていない場合は、カスタムのパフォーマンスサービスレベルを作成できます。ただし、システム定義のパフォーマンスサービスレベルをストレージワークロードに使用し、必要な場合にのみカスタムのパフォーマンスサービスレベルを作成することを推奨します。
