---
permalink: online-help/concept-managing-storage-efficiency-policies.html 
sidebar: sidebar 
keywords: add 
summary: Storage Efficiencyポリシー（SEP \）を使用して、ワークロードのストレージ効率化特性を定義できます。ワークロードの作成時または編集時に、ストレージ効率化ポリシーをワークロードに割り当てることができます。 
---
= ストレージ効率化ポリシーの管理
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Storage Efficiency ポリシー（ SEP ）を使用して、ワークロードのストレージ効率化特性を定義することができます。ワークロードの作成時または編集時に、ストレージ効率化ポリシーをワークロードに割り当てることができます。

Storage Efficiency では、ストレージ利用率を高めてストレージコストを削減するシンプロビジョニング、重複排除、データ圧縮などのテクノロジを使用します。ストレージ効率化ポリシーを作成する際に、これらのスペース削減テクノロジを個別に、または組み合わせて使用することで、ストレージ効率を最大限に高めることができます。ポリシーをストレージワークロードに関連付けると、指定されたポリシー設定がストレージワークロードに割り当てられます。Unified Managerでは、システム定義およびユーザ定義のストレージ効率化ポリシーを割り当てて、データセンターのストレージリソースを最適化できます。

Unified Managerには、システム定義のストレージ効率化ポリシーが2つ用意されています。「高」と「低」です。これらの SEP はデータセンターのほとんどのストレージワークロードに当てはまりますが、システム定義の SEP が要件に合わない場合は独自のポリシーを作成できます。

システム定義のストレージ効率化ポリシー、またはワークロードに現在割り当てられているストレージ効率化ポリシーは変更できません。ワークロードに割り当てられているストレージ効率化ポリシー、または他に使用可能なストレージ効率化ポリシーがない場合、そのストレージ効率化ポリシーは削除できません。

ストレージ効率化ポリシーページには、使用可能なストレージ効率化ポリシーが表示され、追加、編集、削除することができます。このページには、次の情報が表示されます。

[cols="1a,1a"]
|===
| フィールド | 説明 


 a| 
名前
 a| 
ストレージ効率化ポリシーの名前。



 a| 
を入力します
 a| 
システム定義のポリシーかユーザ定義のポリシーか。



 a| 
スペースリザベーション
 a| 
ボリュームがシンプロビジョニングされているか、シックプロビジョニングされているか。



 a| 
重複排除
 a| 
ボリュームで重複排除が有効になっているかどうか。

* `Inline`：ボリュームへの書き込み中に重複排除が実行されます
* `Background`：バックグラウンドで重複排除が実行されます
* `Disable`：ボリュームで重複排除が無効になっています




 a| 
圧縮
 a| 
ボリュームでデータ圧縮が有効になっているかどうか。

* `Inline`：ボリュームへの書き込み中にデータ圧縮が実行されます
* `Background`：データ圧縮はバックグラウンドで実行されます
* `Disable`：ボリュームでデータ圧縮が無効になっています




 a| 
ワークロード
 a| 
ストレージ効率化ポリシーが割り当てられているストレージワークロードの数

|===


== カスタムのストレージ効率化ポリシーを作成する場合のガイドラインを次に示します

既存のストレージ効率化ポリシーがストレージワークロードのポリシー要件を満たしていない場合は、カスタムのストレージ効率化ポリシーを作成できます。ただし、システム定義のストレージ効率化ポリシーをストレージワークロードに使用し、必要な場合にのみカスタムのストレージ効率化ポリシーを作成することを推奨します。
