---
permalink: online-help/concept-volume-performance-explorer-page.html 
sidebar: sidebar 
keywords:  
summary: このページには、クラスタ内のボリュームの詳細なパフォーマンス情報が表示されます。このページのタイトルは、FlexVol ボリュームとFlexGroup ボリュームのどちらを表示しているかによって異なります。 
---
= ハフオオマンス/ホリユウムマタハハフオオマンス/FlexGroupエクス
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
このページには、クラスタ内のボリュームの詳細なパフォーマンス情報が表示されます。このページのタイトルは、FlexVol ボリュームとFlexGroup ボリュームのどちらを表示しているかによって異なります。

ボリュームまたはFlexGroup エクスプローラページでは、一定期間のボリュームのパフォーマンスを追跡して比較することができます。これにより、ボリュームのパフォーマンスのトラブルシューティングや微調整を行うことができます。

[NOTE]
====
ルートボリュームはこのページに表示されません。

====
表示と比較機能の使用：

* FlexVol ボリュームの場合は、このボリュームのパフォーマンスを次の対象と比較できます。
+
** 同じアグリゲート上の他のボリューム
** 同じQoSポリシーグループ内の他のボリューム
** ボリュームが配置されているアグリゲート
** ボリュームが配置されているSVM
** このボリューム上のLUN


* FlexGroup ボリュームの場合は、このFlexGroup のパフォーマンスを次の対象と比較できます。
+
** FlexGroup が配置されているアグリゲート
** FlexGroup が配置されているSVM
** FlexGroup のコンスティチュエントボリューム




グラフに表示される統計は収集期間後に更新されます。この間隔はデフォルトでは5分です。セレクタのView statisticsには、過去1時間の統計を平均化するオプションがあります。この機能を使用して、ネットアップの「パフォーマンス保証」プログラムの状況を確認するためにレイテンシグラフを表示することができます。

パフォーマンス/ボリュームエクスプローラまたはパフォーマンス/ FlexGroupエクスプローラページでは、次の処理を実行できます。

* しきい値に関連する問題とその詳細を表示します
* ボリュームのパフォーマンスデータを追跡して比較する
* しきい値に関連する問題の調査とトラブルシューティング
* パフォーマンスの問題の調査とトラブルシューティング
* System Managerを起動してボリュームの設定を変更します
+
Unified Managerに管理者ロールまたはストレージ管理者ロールでログインしている場合、およびONTAP 9.5以降を使用している場合は、ボリュームの設定*ボタンを使用できます。



[NOTE]
====
データ保護（DP）ボリュームについては、ユーザが生成したトラフィックのカウンタ値のみが表示されます。

====