---
permalink: online-help/concept-monitoring-vms.html 
sidebar: sidebar 
keywords: virtual machines 
summary: 仮想マシン（VM\）アプリケーション上の問題 レイテンシについては、原因 の分析とトラブルシューティングのためにVMの監視が必要になる場合があります。 
---
= 仮想マシンの監視
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
仮想マシン（ VM ）のアプリケーションでレイテンシ問題が発生した場合、原因の分析とトラブルシューティングのために VM の監視が必要になることがあります。

Active IQ Unified Manager では、VMアプリケーションの詳細なトポロジを表示できます。このトポロジには、VMのホストや接続されているデータストアなど、VMが関連するコンポーネントが表示されます。トポロジビューには、基になるコンポーネントが各レイヤの次の順序で表示されます。 * Virtual Disk * > * VM * > * Host * > * Network * > * Datastore * > * VMDK * 。

[NOTE]
====
ストレージレイヤにあるデータストアの指標を表示するには、親のONTAP クラスタをUnified Managerに追加し、クラスタの検出（ポーリングまたは指標の収集）を完了する必要があります。

====
I/O パスとコンポーネントレベルのレイテンシをトポロジの観点から確認し、パフォーマンス問題の原因かどうかを判断できます。トポロジのサマリビューには I/O パスが表示され、解決手順を特定できるように IOPS やレイテンシの問題があるコンポーネントが強調表示されます。また、トポロジの展開ビューで、各コンポーネントとそのコンポーネントのレイテンシを個別に確認することもできます。コンポーネントを選択すると、レイヤ内で強調表示されている I/O パスを確認できます。



== vCenterのデータ収集スケジュール

Unified Managerは、クラスタの構成データの収集と同じスケジュールでvCenterの構成データをポーリングします。vCenterの構成データとパフォーマンスデータの収集スケジュールについては、「クラスタの構成とパフォーマンスのデータの収集アクティビティ」を参照してください。

vCenterは、リアルタイムのパフォーマンスデータのサンプルを20秒間収集して5分ごとのサンプルに集計します。Unified Managerのパフォーマンスデータの収集スケジュールは、vCenter Serverのデフォルトの設定に基づきます。Unified Managerは、vCenterから取得した5分ごとのサンプルを処理し、仮想ディスク、VM、およびホストのIOPSとレイテンシの1時間の平均を計算します。データストアの場合、 Unified Manager は ONTAP から取得したサンプルに基づいて IOPS とレイテンシの 1 時間の平均を計算します。これらの値は毎時 00 分に更新されます。パフォーマンス指標はvCenterを追加した直後には収集されず、次の1時間の開始時にのみ収集されます。パフォーマンスデータのポーリングは、設定データ収集のサイクルが完了すると開始されます。



== トポロジのサマリビューの表示

トポロジのサマリビューでVMを表示してパフォーマンスの問題を特定します

. 「 * vmware * > * Virtual Machines * 」に移動します。
. 検索ボックスに名前を入力して VM を検索します。また、 * フィルター * ボタンをクリックして、特定の条件に基づいて検索結果をフィルターすることもできます。ただし、VMが見つからない場合は、対応するvCenterが追加されて検出されていることを確認してください。
+
[NOTE]
====
vCenter Serverでは、特殊文字（%、&、*、$、#、@、！、\、/、：、*、?、"、<、>、|、；、'）を使用して、VM、クラスタ、データストア、フォルダ、またはfileです。VMware vCenter Server および ESX/ESXi Server では、表示名に使用される特殊文字はエスケープされません。ただし、 Unified Manager で処理される名前は異なって表示されます。たとえば、という名前のVMがあります `%$VC_AIQUM_clone_191124%` vCenter Serverではと表示されます `%25$VC_AIQUM_clone_191124%25` Unified Managerのを参照してください。名前に特殊文字が含まれる VM を照会する場合は、この問題をメモしておく必要があります。

====
. VM のステータスを確認します。VMのステータスはvCenterから取得されます。ステータスは次のいずれかです。これらのステータスの詳細については、 VMware のドキュメントを参照してください。
+
** 正常
** 警告
** アラート
** 監視対象外
** 不明です


. VM の横にある下矢印をクリックすると、コンピューティング、ネットワーク、ストレージの各レイヤにあるコンポーネントのトポロジのサマリビューが表示されます。レイテンシの問題があるノードは強調表示されます。サマリビューには、コンポーネントのワーストレイテンシが表示されます。たとえば、 VM に複数の仮想ディスクがある場合、すべての仮想ディスクの中で最もレイテンシが高い仮想ディスクが表示されます。
. 一定期間にわたるデータストアのレイテンシとスループットを分析するには、データストアオブジェクトアイコンの上にある * Workload Analyzer * ボタンをクリックします。ワークロード分析ページに移動して、期間を選択し、データストアのパフォーマンスチャートを表示できます。Workload Analyzer の詳細については、 Workload Analyzer を使用したワークロードのトラブルシューティング _ を参照してください。
+
link:concept-troubleshooting-workloads-using-the-workload-analyzer.html["Workload Analyzer を使用したワークロードのトラブルシューティング"]





== トポロジの展開ビューの表示

VM のトポロジの展開ビューでは、各コンポーネントにドリルダウンして個別に確認することができます。

. トポロジのサマリビューで、 [* トポロジの展開 *] をクリックします。各コンポーネントの詳細なトポロジが個別に表示され、各オブジェクトのレイテンシを確認できます。データストアまたは VMDK に複数のノードが含まれているカテゴリでは、レイテンシが最も低いノードが赤で強調表示されます。
. 特定のオブジェクトの IO パスを確認するには、そのオブジェクトをクリックして IO パスと対応するマッピングを確認します。たとえば、仮想ディスクのマッピングを表示するには、仮想ディスクをクリックして、対応する VMDK への強調表示されたマッピングを表示します。これらのコンポーネントのパフォーマンスが低下した場合は、 ONTAP からさらに多くのデータを収集し、問題のトラブルシューティングを行うことができます。
+
[NOTE]
====
VMDK については指標は報告されません。トポロジでは、 VMDK 名のみ表示され、指標は表示されません。

====

