---
permalink: online-help/reference-dashboard-page.html 
sidebar: sidebar 
keywords: Dashboard 
summary: Dashboard ページには、監視しているクラスタの容量、パフォーマンス、およびセキュリティの健全性の概要を示すパネルがあります。このページの管理操作パネルには、 Unified Manager が特定のイベントを解決するために実行できる修正が表示されます。 
---
= ダッシュボードページ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ダッシュボード・ページには'パネルがあり'監視対象クラスタの容量'パフォーマンス'セキュリティの健全性の概要が表示されますこのページの管理操作パネルには、 Unified Manager が特定のイベントを解決するために実行できる修正が表示されます。

ほとんどのパネルには、そのカテゴリのアクティブイベントの数および過去 24 時間に追加された新しいイベントの数も表示されます。この情報から、イベントを解決するために詳細な分析が必要なクラスタを決定できます。イベントをクリックすると、上位のイベントが表示され、そのカテゴリのアクティブなイベントをフィルタリングして表示する Event Management インベントリページへのリンクが表示されます。

ダッシュボードの上部で、すべての監視対象クラスタの情報を表示するか、特定のクラスタの情報を表示するかを選択できます。最初にすべてのクラスタのステータスを表示してから、詳細情報を確認する場合は個々のクラスタにドリルダウンできます。

[NOTE]
====
以下のパネルの一部は、構成に応じてページに表示されない場合があります。

====
* * 管理操作パネル *
+
問題によっては、 Unified Manager の詳細な診断によって 1 つの解決策が提供されることがあります。解決策がある場合は、このパネルに*固定*ボタンで表示されます。このような問題は Unified Manager から直接解決できます。 ONTAP System Manager や ONTAP CLI を使用する必要はありません。

+
を参照してください link:concept-fixing-ontap-issues-directly-from-unified-manager.html["ONTAP の問題を Unified Manager から直接修正"] を参照してください。

* * 容量パネル *
+
すべてのクラスタを表示している場合、このパネルには、各クラスタの合計物理容量と使用済み論理容量、ディスクがフルになるまでの予測日数、およびONTAP のStorage Efficiency設定に基づくデータ削減率が表示されます。また、設定されているクラウド階層の使用済み容量も表示されます。棒グラフをクリックすると、そのクラスタのアグリゲートのインベントリページが表示されます。「フルまでの日数」というテキストをクリックすると容量の残り日数が最も少ないアグリゲートを示すメッセージが表示され、そのアグリゲート名をクリックすると詳細が表示されます。

+
単一のクラスタを表示している場合、このパネルには、データアグリゲートの合計物理容量と使用済み論理容量がローカル階層とクラウド階層のそれぞれのディスクタイプでソートされて表示されます。ディスクタイプの棒グラフをクリックすると、そのディスクタイプを使用しているボリュームのボリュームインベントリページが表示されます。

* * パフォーマンス容量パネル *
+
すべてのクラスタを表示している場合、このパネルには、各クラスタのパフォーマンス容量（過去 1 時間の平均）とパフォーマンス容量が上限に達するまでの日数（日次増加率に基づく）が表示されます。棒グラフをクリックすると、そのクラスタのノードインベントリページが表示されます。ノードのインベントリページには過去 72 時間のパフォーマンス容量の平均が表示されるため、この値がダッシュボードの値と一致しないことがあります。「Days to Full」テキストをクリックすると、パフォーマンス容量の残り日数が最も少ないノードを示すメッセージが表示されます。ノード名をクリックすると詳細が表示されます。

+
単一のクラスタを表示している場合、このパネルには、そのクラスタのパフォーマンス容量、合計IOPS、合計スループット（MBps）、およびこれらの3つの指標が上限に達するまでの想定日数が表示されます。

* * ワークロード IOPS パネル *
+
このパネルには、特定の範囲のIOPSで現在実行されているワークロードの総数とディスクタイプ別の内訳が表示されます。

* * ワークロードパフォーマンスパネル *
+
このパネルには、定義された各パフォーマンスサービスレベルに割り当てられている準拠ワークロードと非準拠ワークロードの総数が表示されます。また、 PSL が割り当てられていないアグリゲートの数も表示されます。棒グラフをクリックすると、そのポリシーに割り当てられているワークロードがワークロードページに表示されます。

* * セキュリティパネル *
+
すべてのクラスタを表示している場合、このパネルには、準拠または非準拠のクラスタ数、準拠または非準拠のSVM数、暗号化されたボリュームまたはされていないボリュームの数が表示されます。準拠はに基づいてい https://www.netapp.com/pdf.html?item=/media/10674-tr4569pdf.pdf["ONTAP 9 セキュリティ設定ガイド"^]ます。パネル上部の右矢印をクリックして、 Security ページですべてのクラスタのセキュリティの詳細を表示します。

+
単一のクラスタを表示している場合は、このパネルには、クラスタが準拠しているかどうか、準拠または非準拠のSVM数、暗号化されているボリュームまたはされていないボリュームの数が表示されます。パネル上部の右矢印をクリックして、 Security ページでクラスタのセキュリティの詳細を表示します。

* * 使用状況の概要パネル *
+
すべてのクラスタを表示している場合、 IOPS 、スループット（ MBps ）、または使用済み物理容量が大きい順にクラスタを表示できます。

+
単一のクラスタを表示している場合は、IOPS、スループット（MBps）、または使用済み物理容量が大きい順にワークロードを表示できます。


