---
permalink: online-help/task-viewing-and-adding-vcenter-servers.html 
sidebar: sidebar 
keywords: vCenter server 
summary: 仮想マシン（VM）のパフォーマンスを表示およびトラブルシューティングするには、関連するvCenterをActive IQ Unified Manager インスタンスに追加する必要があります。 
---
= vCenter Serverの表示と追加
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
仮想マシン（VM）のパフォーマンスを表示およびトラブルシューティングするには、関連するvCenterをActive IQ Unified Manager インスタンスに追加する必要があります。



== 作業を開始する前に

vCenterを追加または表示する前に、次の点を確認します。

* vCenterの名前
* vCenterが到達可能で正しく検出される。
* vCenterを追加するためのIPアドレスとクレデンシャルvCenter管理者またはvCenterに読み取り専用でアクセスできるルートユーザのクレデンシャルが必要です。
* 追加するvCenterでvSphere 6.5以降が実行されている
* vCenter Serverにおけるデータ収集は、5分間隔でレベル3に設定されています
* レイテンシ値を正しく計算するために、vCenterのレイテンシ値はマイクロ秒単位ではなくミリ秒単位で設定されている
* vCenterの時刻はvCenterのタイムゾーンに属している




== このタスクについて

Unified Managerは、追加されて検出されたすべてのvCenterについて、vCenterおよびESXiサーバの詳細、ONTAP マッピング、データストアの詳細、ホストされているVMの数などの構成データを収集します。さらに、コンポーネントのパフォーマンス指標も収集されます。



== 手順

. 「* vmware *>* vcenter、*」に移動して、vCenterがリストに表示されているかどうかを確認します。
+
[NOTE]
====
vCenterが表示されない場合は、vCenterを追加する必要があります。

====
+
.. [ 追加（ Add ） ] をクリックします。
.. vCenterの正しいIPアドレスを追加し、デバイスに到達可能であることを確認します。
.. 管理者またはvCenterに読み取り専用でアクセスできるrootユーザのユーザ名とパスワードを追加します。
.. デフォルト以外のポートを使用している場合は、カスタムポート番号を追加します `443`。
.. [ 保存（ Save ） ] をクリックします。検出に成功すると、表示されたサーバ証明書を承認します。
+
証明書を承認すると、vCenterが使用可能なvCenterのリストに追加されます。デバイスを追加しても、関連付けられている VM のデータ収集は開始されず、スケジュールされた間隔で収集されます。



. vCenterのステータスを「* vCenters *」ページで確認します。Status *フィールドにカーソルを合わせると、vCenterが想定どおりに動作しているか、警告またはエラーが発生しているかが表示されます。
+
[NOTE]
====
vCenterを追加すると、次のステータスが表示されます。ただし、vCenterの追加後、対応するVMのパフォーマンスとレイテンシのデータが正確に反映されるまでには最大1時間かかることがあります。

====
+
** 緑：正常。vCenterが検出され、パフォーマンス指標が収集されたことを示します
** 黄：警告（各オブジェクトの統計を取得するためのvCenter Serverの統計レベルが3以上に設定されていない場合など）
** オレンジ：エラー（例外、設定データ収集の失敗、vCenterに到達できないなどの内部エラーを示します）
列表示アイコン（*[表示/非表示]*）をクリックすると、vCenterのステータスに関するステータスメッセージを確認し、問題のトラブルシューティングを行うことができます。


. vCenterに到達できないかクレデンシャルが変更されている場合は、vCenterの詳細を編集します。vCenterを選択し、* Edit *をクリックします。
. VMware vCenter Server の編集 * ページで必要な変更を行います。
. [ 保存（ Save ） ] をクリックします。
+
検出に成功すると、vCenterのステータスが変わります。


