---
permalink: online-help/task-provisioning-fileshares.html 
sidebar: sidebar 
keywords:  
summary: ワークロードのプロビジョニングページでは、利用可能な空きスペースがある場合に、既存のクラスタおよびStorage Virtual Machine（Storage VM）に対してLUN（iSCSIプロトコルとFCPプロトコルの両方をサポート）またはファイル共有（CIFS / SMBプロトコルとNFSプロトコルをサポート）を作成できます。 
---
= ワークロードのプロビジョニング
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ワークロードのプロビジョニングページでは、利用可能な空きスペースがある場合に、既存のクラスタとStorage Virtual Machine（Storage VM）に対してLUN（iSCSIとFCPの両プロトコルをサポート）またはファイル共有（CIFS / SMBとNFSの両プロトコルをサポート）を作成できます。



== 作業を開始する前に

* Storage VMで、SMB、NFS、iSCSI、FCPのうち少なくとも1つのサービスを有効にする必要があります。LUNを作成する場合は、iSCSIとFCPの両方を有効にする必要があります。
* ワークロードにパフォーマンスサービスレベルとストレージ効率化ポリシーを選択して割り当てる場合は、ワークロードの作成を開始する前にポリシーを作成しておく必要があります。




== 手順

. [* Provision Workload *]ページで、作成するワークロードの名前を追加し、ワークロードを作成するクラスタをリストから選択します。
. 選択したクラスタに基づいて、Storage VM *フィールドで、そのクラスタで使用可能なStorage Virtual Machineがフィルタされます。リストから必要な Storage VM を選択します。
+
Storage VMでサポートされているSMB、NFS、iSCSI、FCPの各サービスに基づいて、NASとSANのオプションがホスト情報セクションで有効になります。

. ストレージと最適化*セクションで、ストレージ容量とパフォーマンスサービスレベルを割り当て、必要に応じてワークロードのストレージ効率化ポリシーを割り当てます。
+
パフォーマンスサービスレベルの仕様はワークロードに適用され、ストレージ効率化ポリシーの仕様は、ワークロードの作成時にボリュームとLUNに適宜割り当てられます。

. ワークロードに割り当てたパフォーマンスサービスレベルを適用する場合は、*パフォーマンス制限を適用する*チェックボックスを選択します。ワークロードにパフォーマンスサービスレベルを割り当てることで、ワークロードを作成するアグリゲートが、対応するパフォーマンスサービスレベルで定義されているパフォーマンスと容量の目標をサポートできるようになります。たとえば、ワークロードに「最高レベルのパフォーマンス」が割り当てられている場合、ワークロードをプロビジョニングするアグリゲートには、SSDストレージなど、「最高レベルのパフォーマンス」パフォーマンスサービスレベルのパフォーマンスと容量に関する目標をサポートする機能が必要です。
+
[NOTE]
====
このチェックボックスをオンにしないと、パフォーマンスサービスレベルはワークロードに適用されず、ダッシュボードのワークロードのステータスは「未割り当て」と表示されます。

====
. SMBまたはNFSファイル共有を作成する場合は、* NAS *ボタンを選択します。このボタンは、Storage VMで必要なサービスが有効になっている場合にのみ選択できます。
+
[NOTE]
====
SVMでSMBサービスとNFSサービスの両方が有効になっている場合は、「NFSで共有」ボタンと「SMBで共有」ボタンを選択し、NFSプロトコルとSMBプロトコルの両方をサポートするファイル共有を作成できます。SMB共有とCIFS共有のどちらかを作成する場合は、該当するボタンのみを選択します。

====
+
.. NFSファイル共有の場合は、ファイル共有ボリュームにアクセスするホストまたはネットワークのIPアドレスを指定します。複数のホストの値をカンマで区切って入力できます。
+
ホストのIPアドレスを追加すると、ホストの詳細がSVMと一致しているかどうかがチェックされ、そのホストのエクスポートポリシーが作成されるか、既存のポリシーがある場合はそのポリシーが使用されます。同じホストに対して複数の NFS 共有を作成した場合は、そのホストで使用可能な一致するルールを含むエクスポートポリシーがすべてのファイル共有で再利用されます。API を使用して NFS 共有をプロビジョニングする場合は、個々のポリシーのルールを指定したり、特定のポリシーキーを指定してポリシーを再利用したりすることができます。

.. SMB 共有の場合は、アクセスを許可するユーザまたはユーザグループを指定し、必要な権限を割り当てます。ユーザグループごとに、新しい Access Control List （ ACL ；アクセス制御リスト）がファイル共有の作成時に生成されます。


. LUNを作成するには、* san *ボタンを選択します。このボタンは、選択したStorage VMで必要なサービスが有効になっている場合にのみ選択できます。
+
.. ホスト OS を選択します。
.. LUNのホストマッピングを指定します。既存のイニシエータグループ（igroup）を割り当てるか、または新しいigroupを定義してLUNにマッピングし、どのイニシエータがLUNにアクセスできるかを制御することができます。
+

NOTE: LUNのプロビジョニング時に新しいigroupを作成した場合は、次の検出サイクル（最大15分）でそのigroupが検出されるまでLUNの作成を待つ必要があります。したがって、使用可能な igroup のリストから既存の igroup を使用することを推奨します。

+
新しいigroupを作成する場合は、「*新しいイニシエータグループを作成する*」ボタンを選択し、igroupの作成に必要な情報を入力します。



. [ 保存（ Save ） ] をクリックします。


ワークロードがストレージワークロードのリストに追加されます。
