---
permalink: online-help/task-exporting-storage-data-as-reports.html 
sidebar: sidebar 
keywords:  
summary: データをカンマ区切り値（.csv）ファイルまたはドキュメント（.pdf）にエクスポートし、レポートの作成に使用することができます。たとえば、未解決の重大イベントが10件ある場合、イベント管理インベントリページからデータをエクスポートしてレポートを作成し、それらのイベントに対処することができます。 
---
= レポートを作成するためのCSVファイルおよびPDFファイルへのデータのエクスポート
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
データをカンマ区切り値でエクスポートできます (`.csv`）fileまたは (`.pdf`）をドキュメント化し、エクスポートしたデータを使用してレポートを作成します。たとえば、未解決の重大イベントが10件ある場合、イベント管理インベントリページからデータをエクスポートしてレポートを作成し、それらのイベントに対処することができます。



== このタスクについて

にデータをエクスポートできます `.csv` ファイルまたは `.pdf` ストレージ、ネットワーク、QoSの各インベントリページから文書化し、エクスポートしたデータを使用してレポートを作成します。



== 手順

. 次のいずれかを実行します。
+
[cols="1a,1a"]
|===
| エクスポートする項目 | 手順 


 a| 
イベントの詳細
 a| 
左側のナビゲーションメニューから、 * イベント管理 * をクリックします。



 a| 
ストレージオブジェクトのインベントリの詳細
 a| 
左側のナビゲーションメニューから * Storage * または * Network * をクリックし、ストレージオブジェクトを選択します。次に、* Health *、* Capacity *、* Performance *、* Relationship *ビューのいずれかを選択します。



 a| 
ストレージ容量と保護の履歴の詳細
 a| 
ストレージ * > * アグリゲート * または * ストレージ * > * ボリューム * をクリックして、 1 つまたは複数のアグリゲートまたはボリュームを選択します。



 a| 
上位 10 個のストレージオブジェクトのパフォーマンスの詳細
 a| 
[*ストレージ*>*クラスタ*>*パフォーマンス/すべてのクラスタ*]をクリックし、クラスタを選択して[*パフォーマンストップ*]タブを選択します。次に、ストレージオブジェクトとパフォーマンスカウンタを選択します。



 a| 
QoS ポリシーグループの詳細
 a| 
左側のナビゲーションメニューから、 * Storage * > * QoS Policy Groups * をクリックします。

|===
. [* Export*（エクスポート）]ボタンをクリックします。
. [*CSVファイル*]または[*PDFドキュメント*]をクリックして、エクスポート要求を確定します。
+
Top Performers タブでは、表示している単一のクラスタまたはデータセンター内のすべてのクラスタの統計のレポートをダウンロードできます。

+
ファイルがダウンロードされます。

. を開きます `.csv` ファイルまたは `.pdf` 適切なアプリケーションに文書化します。

