---
permalink: api-automation/concept-data-center-apis.html 
sidebar: sidebar 
keywords:  
summary: データセンターカテゴリのREST APIは、クラスタ、ノード、アグリゲート、ボリューム、LUN、データセンター内のファイル共有、名前空間、およびその他の要素。これらのAPIは、データセンターの設定の照会、追加、削除、変更に使用できます。 
---
= データセンターを管理するためのAPI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
のREST API `datacenter` カテゴリによって、クラスタ、ノード、アグリゲート、ボリューム、LUNに関する情報が提供されます。データセンター内のファイル共有、名前空間、およびその他の要素。これらのAPIは、データセンターの設定の照会、追加、削除、変更に使用できます。

これらの API のほとんどはクラスタをまたいだ集計値を提供する GET 呼び出しで、フィルタ、ソート、およびページ付けをサポートします。これらの API を実行すると、データベースからデータが返されます。したがって、新たに作成されたオブジェクトは、次の取得サイクルで検出されるまで応答に表示されません。

特定のオブジェクトの詳細を照会するには、そのオブジェクトの一意の ID を入力する必要があります。例：

[listing]
----
curl -X GET "https://<hostname>/api/datacenter/cluster/clusters/4c6bf721-2e3f-11e9-a3e2-00a0985badbb" -H "accept: application/json" -H "Authorization: Basic <Base64EncodedCredentials>"
----
[NOTE]
====
cURL コマンド、例、要求、および API への応答は、 Swagger API インターフェイスで参照できます。Swagger にも記載されているとおり、結果を特定のパラメータでフィルタおよび順序付けすることができます。これらの API を使用して、クラスタ、ボリューム、 Storage VM などの特定のストレージオブジェクトについての結果をフィルタリングできます。

====
[cols="1a,1a,4a"]
|===
| HTTP動詞 | パス | 説明 


 a| 
`GET`
 a| 
`/datacenter/cluster/clusters`

`/datacenter/cluster/clusters/{key}`
 a| 
このメソッドを使用して、データセンター全体の ONTAP クラスタの詳細を表示できます。



 a| 
`GET`
 a| 
`/datacenter/cluster/nodes`

`/datacenter/cluster/nodes/{key}`
 a| 
このメソッドを使用して、データセンター内のノードの詳細を表示できます。



 a| 
`GET`
 a| 
`/datacenter/protocols/cifs/shares`

`/datacenter/protocols/cifs/shares/{key}`
 a| 
このメソッドを使用して、データセンター内の CIFS 共有の詳細を表示できます。



 a| 
`GET`
 a| 
`/datacenter/protocols/nfs/export-policies`

`/datacenter/protocols/nfs/export-policies/{key}`
 a| 
このメソッドを使用して、サポートされている NFS サービスのエクスポートポリシーの詳細を表示できます。

このメソッドを使用して、クラスタまたは Storage VM のエクスポートポリシーを照会し、 NFS ファイル共有のプロビジョニングに使用できます。ワークロードでのエクスポートポリシーの割り当てと再利用の詳細については、「 CIFS および NFS ファイル共有のプロビジョニング」を参照してください。



 a| 
`GET`
 a| 
`/datacenter/storage/aggregates`

`/datacenter/storage/aggregates/{key}`
 a| 
このメソッドを使用して、データセンター全体のすべてのアグリゲートを表示し、ワークロードのプロビジョニングや監視を行うことができます。



 a| 
`GET`
 a| 
`/datacenter/storage/luns`

`/datacenter/storage/luns/{key}`
 a| 
このメソッドを使用して、データセンター全体のすべての LUN を表示できます。



 a| 
`GET`
 a| 
`/datacenter/storage/qos/policies`

`/datacenter/storage/qos/policies/{key}`
 a| 
このメソッドを使用して、データセンター内のすべてのQoSポリシーの詳細を表示し、必要に応じてポリシーを適用できます。



 a| 
`GET`
 a| 
`/datacenter/storage/qtrees`

`/datacenter/storage/qtrees/{key}`
 a| 
このメソッドを使用して、データセンター全体のqtreeの詳細を表示できます。



 a| 
`GET`
 a| 
`/datacenter/storage/volumes`

`/datacenter/storage/volumes/{key}`
 a| 
このメソッドを使用して、データセンター内のすべてのボリュームを表示できます。



 a| 
`GET`

`POST`

`DELETE`

`PATCH`
 a| 
`/datacenter/protocols/san/igroups`

`/datacenter/protocols/san/igroups/{key}`
 a| 
特定の LUN ターゲットへのアクセスを許可されたイニシエータグループ（ igroup ）を割り当てることができます。既存の igroup がある場合は、その igroup を割り当てることができます。igroup を作成して、 LUN に割り当てることもできます。

これらのメソッドを使用して、 igroup の照会、作成、削除、および変更を実行できます。

注意事項：

* `POST`：igroupの作成中に、アクセスを割り当てるStorage VMを指定できます。
* `DELETE`：特定のigroupを削除するには、入力パラメータとしてigroupキーを指定する必要があります。すでに LUN に割り当てられている igroup は削除できません。
* `PATCH`：特定のigroupを変更するには、入力パラメータとしてigroupキーを指定する必要があります。また、更新するプロパティとその値を入力する必要があります。




 a| 
`GET`

`POST`

`DELETE`

`PATCH`
 a| 
`/datacenter/svm/svms`

`/datacenter/svm/svms/{key}`
 a| 
これらのメソッドを使用して、 Storage Virtual Machine （ Storage VM ）を表示、作成、削除、および変更できます。

注意事項：

* `POST`：作成するStorage VMオブジェクトを入力パラメータとして指定する必要があります。カスタムの Storage VM を作成して、必要なプロパティを割り当てることができます。
+

NOTE: 環境でSLOベースのワークロードプロビジョニングを有効にしている場合、Storage VMを作成する際には、SMB / CIFS、NFS、FCPなど、LUNとファイル共有のプロビジョニングに必要なすべてのプロトコルがこの環境でサポートされていることを確認してください。およびiSCSIなどです。Storage VM が必要なサービスをサポートしていないと、プロビジョニングワークフローが失敗することがあります。対応するワークロードタイプのサービスも有効にすることを推奨します。

* `DELETE`：特定のStorage VMを削除するには、Storage VMキーを指定する必要があります。
+

NOTE: 環境で SLO ベースのワークロードプロビジョニングを有効にしている場合、ストレージワークロードがプロビジョニングされている Storage VM は削除できません。CIFS / SMBサーバが設定されているStorage VMを削除すると、そのCIFS / SMBサーバとローカルのActive Directory設定も削除されます。ただし、CIFS / SMBサーバ名はActive Directory設定に残っているため、Active Directoryサーバから手動で削除する必要があります。

* `PATCH`：特定のStorage VMを変更するには、Storage VMキーを指定する必要があります。また、更新するプロパティとその値を入力する必要があります。


|===