---
permalink: api-automation/concept-managing-fileshares-api.html 
sidebar: sidebar 
keywords:  
summary: ここに記載されたAPIを使用して、CIFS共有とNFSファイル共有を表示、追加、および削除できます。これらのAPIを使用して、ファイル共有のパフォーマンスサービスレベルポリシーとストレージ効率化ポリシーを割り当てたり変更したりすることもできます。 
---
= ファイル共有の管理
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ここに記載されたAPIを使用して、CIFS共有とNFSファイル共有を表示、追加、および削除できます。これらのAPIを使用して、ファイル共有のパフォーマンスサービスレベルポリシーとストレージ効率化ポリシーを割り当てたり変更したりすることもできます。

ストレージを割り当てる前に、仮想マシンを作成し、サポートされるプロトコルでプロビジョニングしておく必要があります。同様に、ファイル共有にストレージ効率化ポリシーを割り当てる場合は、ファイル共有を作成する前にストレージ効率化ポリシーを作成する必要があります。



== ファイル共有を表示します

Unified Manager環境で使用可能なすべてのストレージワークロードを表示するには、次のメソッドを使用します。Active IQ Unified Manager のデータソースとして ONTAP クラスタを追加すると、それらのクラスタのストレージワークロードが Unified Manager インスタンスに自動的に追加されます。このAPIは、Unified Managerインスタンスに自動および手動で追加されたすべてのファイル共有を取得します。特定のファイル共有の詳細を表示するには、ファイル共有キーを指定してこの API を実行します。

[cols="1a,1a,1a"]
|===
| カテゴリ | HTTP 動詞 | パス 


 a| 
ストレージプロバイダ
 a| 
取得
 a| 
`/storage-provider/file-shares`

`+/storage-provider/file-shares/{key}+`

|===


== ファイル共有を追加

SVM に CIFS および NFS ファイル共有を追加するには、次のメソッドを使用します。作成するファイル共有の詳細を入力パラメータとして指定する必要があります。このAPIを使用してFlexGroupを作成することはできません。

[cols="1a,1a,1a"]
|===
| カテゴリ | HTTP 動詞 | パス 


 a| 
ストレージプロバイダ
 a| 
投稿（ Post ）
 a| 
`/storage-provider/file-shares`

|===
[NOTE]
====
アクセス制御リスト（ ACL ）パラメータまたはエクスポートポリシーパラメータのどちらを指定するかに応じて、 CIFS 共有または NFS ファイル共有が作成されます。ACL パラメータの値を指定しない場合、 CIFS 共有は作成されず、デフォルトで NFS 共有が作成され、すべてのアクセスが提供されます。

====


== ファイル共有を削除します

特定のファイル共有を削除するには、次のメソッドを使用します。特定のファイル共有を削除するには、入力パラメータとしてファイル共有キーを入力する必要があります。

[cols="1a,1a,1a"]
|===
| カテゴリ | HTTP 動詞 | パス 


 a| 
ストレージプロバイダ
 a| 
削除
 a| 
`+/storage-provider/file-shares/{key}+`

|===


== ファイル共有を変更する

ファイル共有を変更し、そのプロパティを更新するには、次のメソッドを使用します。

特定のファイル共有を変更するには、ファイル共有キーを指定する必要があります。また、更新するプロパティとその値を入力する必要があります。

[NOTE]
====
この API の 1 回の呼び出しで更新できるプロパティは 1 つだけです。更新が複数ある場合は、この API を何度でも実行する必要があります。

====
[cols="1a,1a,1a"]
|===
| カテゴリ | HTTP 動詞 | パス 


 a| 
ストレージプロバイダ
 a| 
パッチ
 a| 
`+/storage-provider/file-shares/{key}+`

|===