---
permalink: install-windows/task-changing-the-jboss-password-on-windows.html 
sidebar: sidebar 
keywords:  
summary: 新しいカスタムのJBossパスワードを作成して、インストール時に設定されたデフォルトのパスワードを上書きできます。このタスクはオプションですが、サイトによってはセキュリティ上の理由からUnified Managerのデフォルトのインストール設定とは異なる設定が必要になることがあります。この処理を実行すると、 MySQL へのアクセス時に JBoss で使用するパスワードも変更になります。 
---
= JBoss パスワードを変更しています
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
新しいカスタムのJBossパスワードを作成して、インストール時に設定されたデフォルトのパスワードを上書きできます。このタスクはオプションですが、サイトによってはセキュリティ上の理由からUnified Managerのデフォルトのインストール設定とは異なる設定が必要になることがあります。この処理を実行すると、 MySQL へのアクセス時に JBoss で使用するパスワードも変更になります。



== 作業を開始する前に

* Unified Manager がインストールされている Windows システムに対する admin 権限が必要です。
* MySQLのrootユーザのパスワードが必要です。
* ネットアップが提供するサービスにアクセスできる必要があります `password.bat` ディレクトリ内のスクリプト `\Program Files\NetApp\essentials\bin`。




== 手順

. Unified Manager ホストマシンに admin ユーザとしてログインします。
. Windows サービスコンソールを使用して、次の Unified Manager サービスを停止します。
+
** NetApp Active IQ 取得サービス（ Ocie-au ）
** NetApp Active IQ 管理サーバサービス（ Oncommandsvc ）


. を起動します `password.bat` パスワード変更プロセスを開始するスクリプト： `C:\Program Files\NetApp\essentials\bin> password.bat resetJBossPassword`
. プロンプトが表示されたら、 MySQL root ユーザのパスワードを入力します。
. プロンプトが表示されたら、現在のJBossユーザのパスワードを入力します。
+
デフォルトのパスワードはです `D11h1aMu@79%`。

. プロンプトが表示されたら、新しい JBoss ユーザのパスワードを入力し、確認のためにもう一度入力します。
+
確認メッセージは変更時に一度表示され、最後にもう一度新しいJBossユーザのパスワードを入力するように求められます。

. 新しいJBossユーザのパスワードをもう一度入力します。
. スクリプトが完了したら、 Windows サービスコンソールを使用して Unified Manager サービスを開始します。
+
** NetApp Active IQ 管理サーバサービス（ Oncommandsvc ）
** NetApp Active IQ 取得サービス（ Ocie-au ）


. すべてのサービスが開始されたら、 Unified Manager UI にログインできます。

