---
permalink: config/task-configuring-event-notification-settings.html 
sidebar: sidebar 
keywords:  
summary: Unified Manager では、イベントが生成されたときやユーザに割り当てられたときにアラート通知を送信するように設定することができます。アラートの送信に使用する SMTP サーバを設定したり、さまざまな通知メカニズムを設定したりできます。たとえば、アラート通知を E メールや SNMP トラップとして送信できます。 
---
= イベント通知を設定しています
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager では、イベントが生成されたときやユーザに割り当てられたときにアラート通知を送信するように設定することができます。アラートの送信に使用する SMTP サーバを設定したり、さまざまな通知メカニズムを設定したりできます。たとえば、アラート通知を E メールや SNMP トラップとして送信できます。



== 作業を開始する前に

次の情報が必要です。

* アラート通知の送信元 E メールアドレス
+
メール・アドレスは ' 送信されたアラート通知の送信元フィールドに表示されます何らかの理由で E メールを配信できない場合は、この E メールアドレスが配信不能メールの受信者としても使用されます。

* SMTP サーバのホスト名、およびサーバにアクセスするためのユーザ名とパスワード
* SNMP トラップと SNMP バージョン、アウトバウンドトラップポート、コミュニティ、およびその他の必要な SNMP 設定値を受信するトラップ送信先ホストのホスト名または IP アドレス
+
複数のトラップ送信先を指定するには、各ホストをカンマで区切ります。この場合、バージョンやアウトバウンドトラップポートなど、他の SNMP 設定はすべてリスト内のすべてのホストで同じでなければなりません。



アプリケーション管理者またはストレージ管理者のロールが必要です。



== 手順

. 左側のナビゲーションペインで、 * 一般 * > * 通知 * をクリックします。
. [*Notifications]ページで、適切な設定を構成し、[*Save]をクリックします。
+
[NOTE]
====
....
**If the From Address is pre-filled with the address "ActiveIQUnifiedManager@localhost.com", you should change it to a real, working email address to make sure that all email notifications are delivered successfully.
** If the host name of the SMTP server cannot be resolved, you can specify the IP address (IPv4 or IPv6) of the SMTP server instead of the host name.
....
====

