---
permalink: install-linux/qsg-linux.html 
sidebar: sidebar 
keywords: quick start guide, getting started, QSG, Linux QSG, RHEL QSG, quick installation 
summary: Linux プラットフォームでの Unified Manager のクイックスタートガイドです。 
---
= Linux インストールのクイックスタート手順
:allow-uri-read: 




== システム要件

* オペレーティングシステム：OSインストーラの「ソフトウェアの選択*」オプションから「GUI付きサーバ」ベース環境を使用してインストールされた、x86_64アーキテクチャに基づくRed Hat Enterprise Linuxバージョン7.xおよび8.xまたはCentOSバージョン7.x
* RAM ： 12 GB 、 CPU ：合計 9572MHz
* 空きディスクスペース：100GBのディスクスペースがに表示されます `/opt/netapp/data` ディレクトリ。ルートパーティション内で50GB。別途マウントする必要があります `/opt` および `/var/log` ディレクトリに移動する場合は、を確認します `/opt` 15 GB、 `/var/log` には16GB、およびが搭載されています `/tmp` に10GBの空きスペースがあります。


システム要件の詳細および製品をセキュリティ保護されたサイトにインストールする方法については、を参照してください link:./install-linux/concept-requirements-for-installing-unified-manager.html["Unified Manager をインストールするための要件"] および link:http://mysupport.netapp.com/matrix["互換性マトリックス"]。



== Active IQ Unified Manager をインストールしています



=== インストーラをダウンロードします。

. をダウンロードします `ActiveIQUnifiedManager-<version>.zip` インストールパッケージとコード署名証明書 (`.pem`）およびデジタル署名 (`.sig`）。
. インストールファイルをダウンロードしたディレクトリで、次のコマンドを実行します。
+
`# unzip ActiveIQUnifiedManager-<version>.zip`





=== 整合性を検証

次のコマンドを実行して、インストーラパッケージの整合性を確認します。

* を実行します `openssl x509 -pubkey -noout -in AIQUM-RHEL-CLIENT-INTER-ROOT.pem > <public_key_file_name>` コード署名証明書から公開鍵を使用してファイルを作成するには、次の手順を実行します。
* を実行します `openssl dgst -sha256 -verify <public_key_file_name> -signature <signature_file_name> ActiveIQUnifiedManager-<version>.zip` インストーラパッケージの署名を確認します。




=== リポジトリの構成を確認する

Red Hat Enterprise Linux リポジトリまたは CentOS リポジトリを設定する手順はサイトによって異なります。を使用できます `pre_install_check.sh` インストールパッケージに含まれるスクリプトで、オペレーティングシステムの構成を確認します。システムがインターネットに接続されている場合は、 Red Hat Enterprise Linux リポジトリまたは CentOS リポジトリのセットアップ手順が自動的に表示されます。

`# sudo ./pre_install_check.sh`



=== Unified Manager をインストールします

Unified Managerでは、を使用します `yum` ソフトウェアおよび依存ソフトウェアをインストールするユーティリティ。Red Hat Enterprise Linux または CentOS にはさまざまなイメージがインストールされるため、インストールするパッケージはイメージに含まれるソフトウェアによって異なります。。 `yum` インストールに使用する依存ソフトウェアパッケージは、ユーティリティによって決定されます。依存するソフトウェアパッケージの詳細については、を参照してください link:../install-linux/reference-red-hat-and-centos-software-and-installation-requirements.html["Linux ソフトウェアとインストールの要件"]。

Unified Managerをインストールするには、rootユーザとして、またはを使用して、次のコマンドを実行します `sudo`インストールファイルを解凍したディレクトリで、次の手順を実行します。

`# yum install netapp-um<version>.x86_64.rpm`

または

`% sudo yum install netapp-um<version>.x86_64.rpm`

インストールの完了時に、 Unified Manager Web UI に接続するための情報が表示されます。Web UIに接続できない場合は、を参照してください `README` ポート443の制限の詳細については、ソフトウェアにパッケージ化されたファイルを参照してください。
