---
permalink: install-linux/task-upgrading-mysql-on-linux.html 
sidebar: sidebar 
keywords:  
summary: Unified Managerがインストールされている接続されたLinuxサーバでMySQLを新しいバージョンにアップグレードすることで、セキュリティの脆弱性に対する修正を入手できます。マイナーアップグレードの場合、MySQLの基本バージョンは8.0.20以降である必要があります。システムにインストールされているMySQLのバージョンが8.0.20より前の場合は、Unified Manager 9.7のアップグレードプロセスによってMySQLが8.0.17に自動的にアップグレードされます。旧バージョンから8.0.20へのMySQLのスタンドアロンアップグレードは実行しないでください。 
---
= Linux での MySQL のアップグレード
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Managerがインストールされている接続されたLinuxサーバでMySQLを新しいバージョンにアップグレードすることで、セキュリティの脆弱性に対する修正を入手できます。マイナーアップグレードの場合、MySQLの基本バージョンは8.0.20以降である必要があります。システムにインストールされているMySQLのバージョンが8.0.20より前の場合は、Unified Manager 9.7のアップグレードプロセスによってMySQLが8.0.17に自動的にアップグレードされます。旧バージョンから8.0.20へのMySQLのスタンドアロンアップグレードは実行しないでください。



== 作業を開始する前に

[NOTE]
====
MySQLの手動アップグレードは、インターネットに接続されたシステムにのみ適用されます。システムにインストールされているMySQLのバージョンが5.7の場合は、MySQLをバージョン8.0.20に直接アップグレードしないでください。その結果、アプリケーションのデータが失われます。

====
Unified Manager がインストールされている Linux システムに対する root 権限が必要です。



== このタスクについて

基本バージョンであるMySQL 8.0.20から新しいバージョンへのアップグレードは、マイナーアップデートのみが対象です。



== 手順

. Unified Manager ホストマシンに root ユーザとしてログインします。
. 最新のMySQL Community Serverをダウンロードします `.rpm` ターゲットシステムにバンドルします。
. バンドルをターゲットシステム上のディレクトリに展開します。
. 複数のメリットがあります `.rpm` 展開したバンドルにはパッケージが含まれていますが、Unified Managerで必要とされるのは次のrpmパッケージのみです。
+
** mysql-community-client-8.0.20を参照してください
** mysql-community-libs-8.0.20
** mysql-community-server-8.0.20を参照してください
** mysql-community-common-8.0.20
** mysql-community-libs-compat-8.0.20


+
その他をすべて削除します `.rpm` パッケージ。ただし、 rpm バンドル内のすべてのパッケージをインストールしても、原因エラーは発生しません。

. Unified Manager サービスと関連する MySQL ソフトウェアを次の順序で停止します。
. 次のコマンドを使用して、 MySQL のアップグレードを実行します。 `yum install *.rpm`
+
`*.rpm` を参照します `.rpm` 新しいバージョンのMySQLをダウンロードしたディレクトリ内のパッケージ。

. Unified Manager を次の順序で開始します。

